// Teste da API Rest de prestadores

@baseURL = http://localhost:4000/api/unidades

###
# GET - Lista todos as unidades cadastradas
GET {{baseURL}}/?limit=10&skip=0
Content-Type: application/json

###
# GET - Lista a UBS pelo ID
GET {{baseURL}}/?id=6626c1cc9dc31a6afc66d1ab
Content-Type: application/json

###
# DELETE - Remove a unidade
DELETE {{baseURL}}/661554d59534a7df29d3656a
Content-Type: application/json

###
# POST - Insere uma novA unidade
POST {{baseURL}}
Content-Type: application/json

{
    "nomeUnidade": "UBS - Jardim Serrano",
    "dataCadastro": "2024-08-04",
    "cep": "18115550",
    "endereco": {
        "logradouro": "R.Francisco Lopes de Almeida",
        "numero": 76,
        "complemento": "",
        "bairro": "Jardim Palmira",
        "localidade": "Votorantim",
        "uf": "SP"
    },
    "localizacao": {
        "type": "Point",
        "coordinates": [-23.55866, -47.45476]
    }
}

###
# PUT - Altera um prestador (pelo _id)
PUT {{baseURL}}/?id=6626c1cc9dc31a6afc66d1ab
Content-Type: application/json

{           
     "_id": "6626c1cc9dc31a6afc66d1ab",
    "nomeUnidade": "Teste alterado",
    "dataCadastro": "2024-04-22",
    "cep": "18117133",
    "endereco": {
      "logradouro": "R. Jacques Gonçalves",
      "numero": "256",
      "complemento": "",
      "bairro": "Jardim Serra",
      "localidade": "Votorantim",
      "uf": "SP"
    },
    "localizacao": {
      "type": "Point",
      "coordinates": [
        "27",
        "-47"
      ]
    }
  }